directory: ~/Dropbox/Music/Library
library: ~/Dropbox/Music/Library/.library.blb

plugins:
  - embedart
  - fetchart
  - lastgenre
  - lyrics
  - missing

import:
  incremental: yes
  quiet_fallback: skip
