directory: ~/Dropbox/Music/Library
library: ~/Dropbox/Music/Library/.library.blb

paths:
  singleton: _Non-Album/$artist/$title

plugins:
  - embedart
  - fetchart
  - lastgenre
  - lyrics
  - missing

import:
  incremental: yes
  quiet_fallback: skip
