brew 'eza'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'gitmoji'
brew 'git-delta'
brew 'gnupg'
brew 'neovim'
brew 'pinentry-mac'
brew 'pnpm'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'ruby-build'
brew 'starship'
brew 'tldr'
brew 'tmux'
brew 'tmuxinator'
brew 'zplug'
brew 'zoxide'
brew 'zsh'

tap 'thoughtbot/formulae'
brew 'rcm'

cask_args appdir: '/Applications'
cask '1password'
cask 'arc'
cask 'contexts'
cask 'homebrew/cask/gitup'
cask 'kitty'
cask 'licecap'
cask 'obsidian'
cask 'raycast'
cask 'shottr'
cask 'sublime-text'
cask 'topnotch'
cask 'visual-studio-code'

cask 'font-caskaydia-mono-nerd-font'
cask 'font-fira-code'
cask 'font-fira-code-nerd-font'
cask 'font-fira-mono'
cask 'font-hack'
cask 'font-hack-nerd-font'
cask 'font-ia-writer-mono'
cask 'font-ia-writer-duo'
cask 'font-ia-writer-quattro'
cask 'font-ibm-plex'
cask 'font-intel-one-mono'
cask 'font-monoid'
cask 'font-victor-mono'
cask 'font-source-code-pro'
cask 'font-work-sans'

mas 'Fantastical', id: 975937182
mas 'Flow', id: 1423210932
mas 'Googly Eyes', id: 6743048714 
mas 'HazeOver', id: 430798174
mas 'iA Writer', id: 775737590
mas 'Things', id: 904280696

