tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'

cask_args appdir: '/Applications'

brew 'bat'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'git-delta'
brew 'gitmoji'
brew 'htop'
brew 'hub'
brew 'jq'
brew 'mas'
brew 'nodenv'
brew 'pnpm'
brew 'pop'
brew 'ranger'
brew 'rename'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'ruby-build'
brew 'starship'
brew 'tldr'
brew 'tmux'
brew 'tmuxinator'
brew 'yarn'
brew 'yq'
brew 'zplug'
brew 'zsh'

tap 'thoughtbot/formulae'
brew 'rcm'

# cask '1password'
# cask '1password-cli'
cask 'arc'
cask 'contexts'
cask 'discord'
cask 'gitup'
cask 'insomnia'
cask 'iterm2'
cask 'keycastr'
cask 'licecap'
cask 'meetingbar'
cask 'obsidian'
cask 'raindropio'
cask 'raycast'
cask 'readdle-spark'
cask 'shottr'
cask 'sublime-text'
cask 'visual-studio-code'
cask 'warp'

tap 'homebrew/cask-fonts'
cask 'font-fantasque-sans-mono'
cask 'font-fira-code'
cask 'font-fira-code-nerd-font'
cask 'font-hack'
cask 'font-hack-nerd-font'
cask 'font-source-code-pro'
cask 'font-ia-writer-mono'
cask 'font-ia-writer-duo'
cask 'font-ia-writer-quattro'
cask 'font-ibm-plex'
cask 'font-iosevka'
cask 'font-iosevka-nerd-font'
cask 'font-jetbrains-mono'
cask 'font-monoid'
cask 'font-victor-mono'
cask 'font-work-sans'

mas 'Fantastical 2', id: 975937182
mas 'Flow - Focus & Pomodoro Timer', id: 1423210932
mas 'HazeOver • Distraction Dimmer™', id: 430798174
# mas 'Logic Pro', id: 634148309
mas 'Things 3', id: 904280696
# mas 'Xcode', id: 497799835
