if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif
au VimEnter * PlugInstall

call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'terryma/vim-multiple-cursors'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'ap/vim-css-color'
Plug 'scrooloose/nerdtree'
Plug 'https://github.com/jdkanani/vim-material-theme.git', { 'dir': '~/.vim/plugged/vim-material-theme', 'do': 'mv colors/material-theme.vim ~/.vim/colors/' }
Plug 'https://github.com/herrbischoff/cobalt2.vim.git', { 'dir': '~/.vim/plugged/cobalt2.vim.git', 'do': 'mv colors/cobalt2.vim ~/.vim/colors/' }

" Really nice prompt
" Plug 'bling/vim-airline'
" let g:airline_theme='powerlineish'
" let g:airline_left_sep=''
" let g:airline_right_sep=''
" let g:airline_section_z=''

" Awesome autocompletion
" Plug 'Valloric/YouCompleteMe', { 'do': './install.sh' }
call plug#end()

set guifont=Inconsolata
set guioptions=cemg

set number
" Toggle line numbers
:nmap <C-N><C-N> :set invnumber<CR>

" Shift indents with Command+[ or ]
map <D-]> >gv
nmap <D-]> >>
imap <D-]> <Esc><D-]>
map <D-[> <gv
nmap <D-[> <<
imap <D-[> <Esc><D-[>

" Map the leader key to SPACE
let mapleader="\<SPACE>"

" Use ; for commands.
nnoremap ; :

" Open file menu
nnoremap <Leader>o :CtrlP<CR>
" Open buffer menu
nnoremap <Leader>b :CtrlPBuffer<CR>
" Open most recently used files
nnoremap <Leader>f :CtrlPMRUFiles<CR>

" set vb
" set bs=2
" set foldmethod=manual
syntax on
set mouse=a
set colorcolumn=140
let mapleader = " "

set nocompatible
set modelines=0

" Whitespace
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set visualbell
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2

" Quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Open new split panes to right and bottom, which feels more natural
" set splitbelow
" set splitright

" Quicker splits
" nnoremap <Leader>l :vsp<CR>
" nnoremap <Leader>j :sp<CR>

" buffer
nmap <leader>h :leftabove  vnew<CR>
nmap <leader>l :rightbelow vnew<CR>
nmap <leader>k :leftabove  new<CR>
nmap <leader>j :rightbelow new<CR>

" NERDTree
let NERDTreeShowHidden=1
au VimEnter * NERDTree
map <D-\> :NERDTreeToggle<CR>

" ctrlp
let g:ctrlp_max_files=0
let g:ctrlp_max_depth=40
let g:ctrlp_working_path_mode = ''
let g:ctrlp_user_command = ['.git/', 'cd %s && git ls-files --exclude-standard -co']

" vim-material-theme
syntax enable
set background=dark
" colorscheme material-theme
colorscheme cobalt2
