command_timeout = 1500

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""

[directory]
fish_style_pwd_dir_length = 1
style = "bold fg:112"

[git_branch]
style = "bold fg:1"

[git_status]
stashed = ""
style = "bold fg:172"
