#!/bin/bash

# VS Code
mkdir -p "$HOME/Library/Application Support/Code/User/snippets"
ln -sf "${HOME}/.dotfiles/vscode/User/settings.json" "${HOME}/Library/Application Support/Code/User/settings.json"
ln -sf "${HOME}/.dotfiles/vscode/User/keybindings.json" "${HOME}/Library/Application Support/Code/User/keybindings.json"
ln -sf "${HOME}/.dotfiles/vscode/User/snippets" "${HOME}/Library/Application Support/Code/User/snippets"

# TaskPaper
mkdir -p "$HOME/Library/Application Support/TaskPaper/StyleSheets"
ln -sf "${HOME}/TaskPaper/StyleSheets/iA Writer.less" "$HOME/Library/Application Support/TaskPaper/StyleSheets/ia Writer.less"
ln -sf "${HOME}/TaskPaper/StyleSheets/iA Writer Night Mode.less" "$HOME/Library/Application Support/TaskPaper/StyleSheets/ia Writer Night Mode.less"
ln -sf "${HOME}/TaskPaper/StyleSheets/Light.less" "$HOME/Library/Application Support/TaskPaper/StyleSheets/Light.less"

# node
nodenv install 10.13.0

# rbenv
rbenv install 2.5.3

# tmuxinator
gem install tmuxinator
