#!/bin/bash

# VS Code
mkdir -p "$HOME/Library/Application Support/Code/User/snippets"
ln -sf "${HOME}/.dotfiles/vscode/User/settings.json" "${HOME}/Library/Application Support/Code/User/settings.json"
ln -sf "${HOME}/.dotfiles/vscode/User/keybindings.json" "${HOME}/Library/Application Support/Code/User/keybindings.json"
ln -sf "${HOME}/.dotfiles/vscode/User/snippets" "${HOME}/Library/Application Support/Code/User/snippets"
