#!/usr/bin/env bash
function gem_install_or_update() {
  if gem list "$1" --installed > /dev/null; then
    gem update "$@"
  else
    gem install "$@" --no-document
  fi
}

function install_zgen() {
  echo "Installing zgen"
  cd ~
  if [ -d "${HOME}/.zgen" ]; then
    git -C "${HOME}/.zgen" pull
  else
    git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"
  fi
  cd -
}

function install_homesick() {
  echo "Installing dotfiles homesick castle"
  gem_install_or_update homesick
  homesick clone chrislopresto/dotfiles
  homesick pull dotfiles
  homesick unlink dotfiles
  homesick symlink dotfiles --force
  homesick list
}

function setup_sublime_text() {
  echo "Setting up Sublime Text"
  cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/
  rm -r User
  ln -s ~/.homesick/repos/dotfiles/sublime/Packages/User
  cd -
}

function install_homebrew_dependencies() {
  brew tap 'homebrew/bundle'
  brew tap 'caskroom/cask'
  brew tap 'caskroom/fonts'
  brew tap 'caskroom/versions'
  brew tap 'homebrew/core'
  brew tap 'homebrew/services'
  brew tap 'homebrew/versions'
  brew tap 'neovim/neovim'
  if [ -f "$HOME/.dotfiles/home/.Brewfile" ]; then
    echo "Installing Homebrew Dependencies from $HOME/.dotfiles/home/.Brewfile"
    brew bundle --file="$HOME/.dotfiles/home/.Brewfile"
  else
    echo "Installing Homebrew Dependencies"
    brew bundle --global
  fi
}

function install_ruby_gems() {
  echo "Installing ruby gems"
  gem_install_or_update bundler

  gem_install_or_update cocoapods
  gem_install_or_update pry-theme
  gem_install_or_update tmuxinator
}

function install_npm_packages() {
  echo "Installing node versions"
  nodenv init
  nodenv install 6.9.4

  echo "Installing npm packages"
  yarn global upgrade bower ember-cli phantomjs hpm-cli eslint grunt-cli webpack@beta
}

function install_python_packages() {
  echo "Installing python packages"
  pip install -U cider
  pip install -U requests
}

function restore_cider() {
  echo "Restoring cider"
  cider restore
}

function cleanup_after_strap() {
  echo "Cleaning up after strap"
  rm -rf "${HOME}/.dotfiles"
}

install_zgen
install_homebrew_dependencies
install_homesick
install_ruby_gems
install_npm_packages
install_python_packages
restore_cider
setup_sublime_text
cleanup_after_strap
