#!/usr/bin/env bash
function gem_install_or_update() {
  if gem list "$1" --installed > /dev/null; then
    gem update "$@"
  else
    gem install "$@" --no-document
  fi
}

function install_zgen() {
  echo "Installing zgen"
  cd ~
  if [ -d "${HOME}/.zgen" ]; then
    git -C "${HOME}/.zgen" pull
  else
    git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"
  fi
  cd -
}

function install_ellipsis_dotfiles() {
  echo "Installing ellipsis"
  curl -sL ellipsis.sh | sh
  ~/.ellipsis/bin/ellipsis install https://github.com/chrislopresto/dotfiles
}

function install_homebrew_dependencies() {
  brew tap 'homebrew/bundle'
  brew tap 'caskroom/cask'
  brew tap 'caskroom/fonts'
  brew tap 'caskroom/versions'
  brew tap 'homebrew/core'
  brew tap 'homebrew/services'
  brew tap 'homebrew/versions'
  brew tap 'neovim/neovim'
  if [ -f "$HOME/.Brewfile" ]; then
    echo "Installing Homebrew Dependencies"
    brew bundle --global
  elif [ -f "$HOME/.ellipsis/packages/dotfiles/.Brewfile" ]; then
    echo "Installing Homebrew Dependencies from $HOME/.ellipsis/packages/dotfiles/.Brewfile"
    brew bundle --file="$HOME/.ellipsis/packages/dotfiles/.Brewfile"
  else
    echo "Installing Homebrew Dependencies from $HOME/.dotfiles/.Brewfile"
    brew bundle --file="$HOME/.dotfiles/.Brewfile"
  fi
}

function install_ruby_gems() {
  echo "Installing ruby gems"
  gem_install_or_update bundler
  gem_install_or_update pry-theme
  gem_install_or_update tmuxinator
}

function install_npm_packages() {
  echo "Installing node versions"
  nodenv init
  nodenv install 6.9.4

  echo "Installing npm packages"
  yarn global upgrade bower ember-cli phantomjs hpm-cli eslint sass-lint grunt-cli webpack@beta
}

function install_python_packages() {
  echo "Installing python 3.5.0"
  pyenv install 3.5.0
  pyenv local 3.5.0

  echo "Installing python packages"
  pip3 install -U cider
  pip3 install -U requests
  pip3 install neovim
}

function install_rust() {
  echo "Installing rust"
  curl https://sh.rustup.rs -sSf | sh
}

function restore_cider() {
  echo "Restoring cider"
  cider restore
}

function cleanup_after_strap() {
  echo "Cleaning up after strap"
  rm -rf "${HOME}/.dotfiles"
}

install_zgen
install_ellipsis_dotfiles
install_homebrew_dependencies
install_ruby_gems
install_npm_packages
install_python_packages
install_rust
restore_cider
cleanup_after_strap
