#!/bin/bash
set -uxo pipefail

DOTFILES="$HOME/.dotfiles"

function setup_homebrew() {
  if ! type brew 2>/dev/null; then
    if [ -d /opt/homebrew ]; then
      echo 'brew found in /opt/homebrew. Assuming Apple Silicon.'
      echo 'Adding brew to path'
      echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >>"/Users/$USER/.profile"
      eval "$(/opt/homebrew/bin/brew shellenv)"
    else
      echo 'brew not found on path. /opt/homebrew directory not found on disk.'
    fi
  fi
  if [ -f "$HOME/.Brewfile" ]; then
    brew update
    brew bundle --global
  elif [ -f "$DOTFILES/Brewfile" ]; then
    # on first run, rcup hasn't run yet, so
    # let's brew bundle from a special location
    brew update
    brew bundle --file="$DOTFILES/Brewfile"
  fi
}

function setup_fish_shell() {
  if ! grep -q '/opt/homebrew/bin/fish' /etc/shells; then
    echo 'Homebrew fish shell is not in shells list, adding...'
    echo '/opt/homebrew/bin/fish' | sudo tee -a /etc/shells
  fi

  if [[ "$SHELL" != '/opt/homebrew/bin/fish' ]]; then
    echo 'Current shell is not homebrew fish, switching...'
    chsh -s /opt/homebrew/bin/fish
  fi
}

function setup_macos() {
  echo 'Tweaking macOS settings'
  defaults write -g ApplePressAndHoldEnabled -bool false
  defaults write -g InitialKeyRepeat -int 12 # normal minimum is 15 (225 ms)
  defaults write -g KeyRepeat -int 1         # normal minimum is 2 (30 ms)

  # Use list view in all Finder windows by default
  # Four-letter codes for the other view modes: `icnv`, `clmv`, `glyv`
  defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"
}

function setup_tools() {
  echo 'Installing tools'
  mise settings add idiomatic_version_file_enable_tools node
  mise settings add idiomatic_version_file_enable_tools python
  mise settings add idiomatic_version_file_enable_tools ruby

  # Prepare to set up mise autocompletion
  mise use -g usage

  # install preferred tool versions
  mise use --global \
    node@latest \
    python@latest \
    ruby@latest

  # set up global versions of common tools
  mise use --global \
    npm:markdownlint-cli2
}

setup_homebrew
setup_fish_shell
setup_macos
setup_tools
