#!/bin/bash
set -uxo pipefail

DOTFILES="$HOME/.dotfiles"

function setup_zplug() {
  echo 'Installing zplug'
  cd ~
  if [ -d "${HOME}/.zplug" ]; then
    git -C "${HOME}/.zplug" pull
  else
    git clone https://github.com/zplug/zplug.git "${HOME}/.zplug"
  fi
  cd -
}

function setup_homebrew() {
  if ! type brew 2> /dev/null; then
    if [ -d /opt/homebrew ]; then
      echo 'brew found in /opt/homebrew. Assuming Apple Silicon.'
      echo 'Adding brew to path'
      eval "$(/opt/homebrew/bin/brew shellenv)"
    else
      echo 'brew not found on path. /opt/homebrew directory not found on disk.'
    fi
  fi
  if [ -f "$HOME/.Brewfile" ]; then
    brew update
    brew bundle --global
  elif [ -f "$DOTFILES/Brewfile" ]; then
    # on first run, rcup hasn't run yet, so
    # let's brew bundle from a special location
    brew update
    brew bundle --file="$DOTFILES/Brewfile"
  fi
}

function setup_zsh() {
  echo 'Changing to brew-installed zsh'
  if [ -d /opt/homebrew ]; then
    echo 'brew found in /opt/homebrew. Assuming Apple Silicon.'
    sudo dscl . -create /Users/$USER UserShell /opt/homebrew/bin/zsh
  else
    echo '/opt/homebrew directory not found. Assuming macOS Intel.'
    sudo dscl . -create /Users/$USER UserShell /usr/local/bin/zsh
  fi
}

function setup_node() {
  echo 'Installing node'
  nodenv install 14.15.4
  nodenv rehash
}

function setup_ruby() {
  echo 'Installing ruby'
  rbenv install 3.0.0
  rbenv rehash
}

function setup_macos() {
  echo 'Tweaking macOS settings'
  defaults write -g ApplePressAndHoldEnabled -bool false
  defaults write -g InitialKeyRepeat -int 12 # normal minimum is 15 (225 ms)
  defaults write -g KeyRepeat -int 1 # normal minimum is 2 (30 ms)
}

setup_zplug
setup_homebrew
setup_zsh
setup_node
setup_ruby
setup_macos
