# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_FONTS
font_family      family="CaskaydiaMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 12.0
modify_font cell_height 100%

enable_audio_bell no
visual_bell_duration 0.5 ease-in-out

hide_window_decorations yes
window_padding_width 5 5 0

copy_on_select yes
confirm_os_window_close 0

tab_bar_edge bottom
tab_bar_style powerline
tab_title_template "{'★ ' if layout_name == 'stack' else ''}{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title} {sup.index}"

macos_option_as_alt yes
macos_quit_when_last_window_closed yes

enabled_layouts splits:split_axis=vertical,stack
map ctrl+a>v launch --location=vsplit --cwd=current
map ctrl+a>s launch --location=hsplit --cwd=current
map ctrl+shift+enter launch --cwd=current

# shell bash
shell_integration disabled
allow_remote_control yes
listen_on unix:/tmp/mykitty
map ctrl+h kitten pass_keys.py left   ctrl+h
map ctrl+j kitten pass_keys.py bottom ctrl+j
map ctrl+k kitten pass_keys.py top    ctrl+k
map ctrl+l kitten pass_keys.py right  ctrl+l

map ctrl+a>h resize_window narrower 5
map ctrl+a>j resize_window taller 6
map ctrl+a>k resize_window shorter 5
map ctrl+a>l resize_window wider 5

map ctrl+a>c new_tab
map ctrl+a>n next_tab
map ctrl+a>p previous_tab
map ctrl+a>1 goto_tab 1
map ctrl+a>2 goto_tab 2
map ctrl+a>3 goto_tab 3
map ctrl+a>4 goto_tab 4
map ctrl+a>5 goto_tab 5
map ctrl+a>6 goto_tab 6
map ctrl+a>7 goto_tab 8
map ctrl+a>8 goto_tab 8
map ctrl+a>9 goto_tab 9

map cmd+w close_window
map cmd+shift+w close_tab
map ctrl+a>z toggle_layout stack
map ctrl+a>r load_config_file

scrollback_pager nvim +"source ~/.config/kitty/vim-scrollback.lua"
map ctrl+a>/ show_scrollback

include ${HOME}/.config/dotfiles/current/theme/kitty.conf
include ${KITTY_OS}.conf
